export const data = {
  products: [
    {
      _id: "1",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "2",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      countInStock: 0,
      brand: "Nike",
      rating: 1.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "3",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      countInStock: 2,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "4",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      countInStock: 5,
      brand: "Nike",
      rating: 2.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "6",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      countInStock: 12,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "5",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      countInStock: 8,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
  ],
};
