export const data = {
  products: [
    {
      _id: "1",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "2",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "3",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "4",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "6",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "5",
      name: "Nike S Shirt",
      category: "Shirts",
      image: "",
      price: 150,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality product",
    },
  ],
};
